/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/*
imports an arraylist which is used for playerScore , playerName and more.
arraylist is a list of arrays.
*/
import java.util.ArrayList;
// imports some main JFrame features.
//Also used to call the other JFrame
import javax.swing.JFrame;
/*
*Imports random number genartor which gives us the random dice number
*/
import java.util.Random;
// imports imageIcon used to display the dice in the main screen
import javax.swing.ImageIcon;
// imports joptionpane which is basically a window pop up
import javax.swing.JOptionPane;
        
/**
 *
 * @author Rei
 */

public class NewJFrame extends javax.swing.JFrame {
    /*
    over here i have declared all of variables and arrayLists which i have used
    in my project
    Also the place where i have loaded in the dice image
    */
    static int number;
    static String player1, player2;
    //static ArrayList<Integer> randomN = new ArrayList<Integer>();
    int perRole=0;
    int total = 0;
    int perRoleTwo=0;
    int totalTwo=0;
    boolean currentPlayer=true;
    //declared all the arraylists
    static ArrayList<Integer> gameNumber = new ArrayList<Integer>();
     ArrayList<Integer> playerScore = new ArrayList<Integer>();
     ArrayList<String> playerName = new ArrayList<String>(); 
     //load dice image
    ImageIcon Dice = new ImageIcon("diceee.png");
   
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        // display dice image in imageLbl
        imageLbl.setIcon(Dice);
        //get player one name using JOptionPane
        player1 = JOptionPane.showInputDialog("Text ", "Input name of player 1");
        currentPlayerLbl.setText(player1);
        player1Lbl.setText(player1);
        //player 2 name is hardcoded
        player2="Robot";
        
        String message = "No numbers";
        
        
        //if player enters numbers , shoe error msg and stop the game
        if (player1.matches("[0-9]"))
        {
             JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
             System.exit(0);
                  
        } else {
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        player1Lbl = new javax.swing.JLabel();
        rollDice = new javax.swing.JButton();
        holdDice = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        playerOnePointsTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        playerTwoTotal = new javax.swing.JTextField();
        currentPlayerLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        player1TF = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        player2TF = new javax.swing.JTextArea();
        imageLbl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Robot");

        player1Lbl.setText("Player 1");

        rollDice.setText("Roll");
        rollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollDiceActionPerformed(evt);
            }
        });

        holdDice.setText("Hold");
        holdDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holdDiceActionPerformed(evt);
            }
        });

        jLabel3.setText("Current Player");

        jLabel4.setText("Total");

        playerOnePointsTotal.setEditable(false);
        playerOnePointsTotal.setText("0");
        playerOnePointsTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerOnePointsTotalActionPerformed(evt);
            }
        });

        jLabel5.setText("Total");

        playerTwoTotal.setEditable(false);
        playerTwoTotal.setText("0");

        player1TF.setEditable(false);
        player1TF.setColumns(20);
        player1TF.setRows(5);
        player1TF.setAutoscrolls(false);
        jScrollPane1.setViewportView(player1TF);

        player2TF.setEditable(false);
        player2TF.setColumns(20);
        player2TF.setRows(5);
        jScrollPane2.setViewportView(player2TF);

        jMenu1.setText("File");

        jMenuItem1.setText("Search Game by Date");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Show Games History");
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem4.setText("About");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imageLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(player1Lbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(playerOnePointsTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rollDice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(holdDice))
                            .addComponent(currentPlayerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(playerTwoTotal))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentPlayerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rollDice)
                            .addComponent(holdDice)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(player1Lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(playerOnePointsTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(playerTwoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void rollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollDiceActionPerformed
        
        // ROLL DICE
       //roll random number
            Random r = new Random();
            //currentplayer==true means player one
            //currentplayer==false means player two
            
            if(currentPlayer==true){
                int randomNum =r.nextInt(1,7);
                perRole+=randomNum;
                 //display text in player 1 text field
                player1TF.setText(player1TF.getText()+randomNum+"\n");
                currentPlayerLbl.setText(player1);
                
              //if dice roll is 1 for player 1 >> do that   
            if (randomNum==1){
                //Remove points from player1
                //player to false
                
                currentPlayer=false;
                perRole=0;
                total=0;
                player2TF.setText("");
            }
                
            }
            
            //if dice roll is 1 for player 2 to do that
            if (currentPlayer==false){
                
                int randomNum =r.nextInt(1,7);
                perRoleTwo+=randomNum;
                //display number in player 2 text field
                player2TF.setText(player2TF.getText()+randomNum+"\n");
                currentPlayerLbl.setText("robot");
             
                if (randomNum==1){
                //Remove points from player1
                //player to false
                
                currentPlayer=true;
                perRoleTwo=0;
                totalTwo=0;
                player1TF.setText("");
            }
            }
                  
    }//GEN-LAST:event_rollDiceActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // EXIT GAME
        //confirm for exiting the app using JOptionpane
     int confirmed = JOptionPane.showConfirmDialog(null, "Exit Program?","EXIT",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            //does not close the app only disposes it
            dispose();
        }
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // calls another jframe which is called "About"
        // for the about section
        About jf2 = new About();
        jf2.show();
       
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void playerOnePointsTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerOnePointsTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerOnePointsTotalActionPerformed

    private void holdDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holdDiceActionPerformed
        // TODO add your handling code here:
        if (currentPlayer==true){
            total+=perRole;
            perRole=0;
            currentPlayer=false;
            playerOnePointsTotal.setText(Integer.toString(total));
            player2TF.setText("");
            //if player one has more than 99 points display player1+wins
            if (total > 99){
                playerOnePointsTotal.setText(player1+"Wins");
                //add total points of player one and player two
                // to the arraylist called playerScore
                playerScore.add(total,totalTwo);
            }
        }
        if(currentPlayer==false){
            totalTwo+=perRoleTwo;
            perRoleTwo=0;
            currentPlayer=true;
            playerTwoTotal.setText(Integer.toString(totalTwo));
            player1TF.setText("");
            //if player Two has more than 99 points display player2+wins
            if (totalTwo>99){
                playerTwoTotal.setText(player2+("wins"));
                //add total points of player one and player two
                // to the arraylist called playerScore
                playerScore.add(total,totalTwo);
            }
        }
    }//GEN-LAST:event_holdDiceActionPerformed

    /**
     * @param args the command line arguments
     */
   
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentPlayerLbl;
    private javax.swing.JButton holdDice;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel player1Lbl;
    private javax.swing.JTextArea player1TF;
    private javax.swing.JTextArea player2TF;
    private javax.swing.JTextField playerOnePointsTotal;
    private javax.swing.JTextField playerTwoTotal;
    private javax.swing.JButton rollDice;
    // End of variables declaration//GEN-END:variables

   
 
}
